# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

homepage:
    path: /
    defaults: { _controller: 'Metinet\Controller\HomeController::index' }

hello:
    path: /hello/{name}
    defaults:
        _controller: 'Metinet\Controller\HomeController::hello'
    requirements:
        name: '[a-zA-Z]+'

students_register:
    path: /students/register
    defaults:
        _controller: 'Metinet\Controller\StudentsController::register'
    methods: [GET,POST]

students_view_profile:
    path: /students/profile/{id}
    defaults:
        _controller: 'Metinet\Controller\StudentsController::viewProfile'
    requirements:
        id: '[0-9a-zA-Z\-]+'
