# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

homepage:
    path: /
    defaults: { _controller: 'Metinet\Controller\HomeController::index' }

hello:
    path: /hello/{name}
    defaults:
        _controller: 'Metinet\Controller\HomeController::hello'
    requirements:
        name: '[a-zA-Z]+'

students_register:
    path: /students/register
    defaults:
        _controller: 'Metinet\Controller\StudentsController::register'
    methods: [GET,POST]

students_view_profile:
    path: /students/profile/{id}
    defaults:
        _controller: 'Metinet\Controller\StudentsController::viewProfile'
    requirements:
        id: '[0-9a-zA-Z\-]+'

blog_latest_posts:
    path: /blog
    defaults:
        _controller: 'Metinet\Controller\BlogController::latestPosts'

blog_new_post:
    path: /blog/new
    defaults:
        _controller: 'Metinet\Controller\BlogController::newPost'
    methods: [GET,POST]

blog_edit_post:
    path: /blog/edit/{postId}
    defaults:
        _controller: 'Metinet\Controller\BlogController::editPost'
    methods: [GET,POST]

blog_view_post:
    path: /blog/{slug}/{id}
    defaults:
        _controller: 'Metinet\Controller\BlogController::viewPost'

security_login:
    path: /login
    defaults:
        _controller: 'Metinet\Controller\SecurityController::login'

security_logout:
    path: /logout
